# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Job Positions
email: jobs@primetag.net
description: > # this means to ignore newlines until "baseurl:"
  Open job positions at Primetag. Primetag is a young, ambitious 
  and growing tech company, working towards fundamentally empowering 
  the influence world. Using engineering and innovation Primetag 
  tackles the most profound problem hovering the advertising sector.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jobs.primetag.net" # the base hostname & protocol for your site
twitter_username: helloprimetag
github_username:  primetag

# Build settings
markdown: kramdown
permalink: /:categories/:title.html